// Configuration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class Configuration {
    
    
    /// If a HTTP status code is outside of this range the response will be interpreted as failed.
    static var successfulStatusCodeRange: Range = 200..<300
}
