use_frameworks!

platform :ios, '10.0'

target 'KindeSDK_Example' do
  pod 'KindeSDK', :path => '../'

  pod 'SwiftLint'

  target 'KindeSDK_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'MockingbirdFramework'
  end
end
