//
//  KindeSDK_Tests-KindeSDK_ExampleMocks.generated.swift
//  KindeSDK_Example
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

// swiftlint:disable all

@testable import KindeSDK_Example
@testable import Mockingbird
import Foundation
import KindeSDK
import Swift
import UIKit
import os.log

// No mocks used in 'KindeSDK_Tests'. Mockingbird is configured to only generate mocks for types
// that are explicitly initialized in your tests with `mock(SomeType.self)`. For more information,
// see 'Thunk Pruning' in the README.
