//
//  KindeAuthSwift_Tests-KindeAuthSwift_ExampleMocks.generated.swift
//  KindeAuthSwift_Example
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

// swiftlint:disable all

@testable import KindeAuthSwift_Example
@testable import Mockingbird
import Foundation
import KindeAuthSwift
import Swift
import UIKit
import os.log

// No mocks used in 'KindeAuthSwift_Tests'. Mockingbird is configured to only generate mocks for
// types that are explicitly initialized in your tests with `mock(SomeType.self)`. For more
// information, see 'Thunk Pruning' in the README.
