//
// UsersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


open class UsersAPI {

    /**
     * enum for parameter sort
     */
    public enum Sort_getUsers: String, CaseIterable {
        case nameAsc = "name_asc"
        case nameDesc = "name_desc"
        case emailAsc = "email_asc"
        case emailDesc = "email_desc"
    }

    /**
     Returns a paginated list of end-user records for a business
     
     - parameter sort: (query) Describes the field and order to sort the result by (optional)
     - parameter pageSize: (query) The number of items to return (optional)
     - parameter userId: (query) The id of the user to filter by (optional)
     - parameter nextToken: (query) A string to get the next page of results if there are more results (optional)
     - returns: Users
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getUsers(sort: Sort_getUsers? = nil, pageSize: Int? = nil, userId: Int? = nil, nextToken: String? = nil) async throws -> Users {
        return try await getUsersWithRequestBuilder(sort: sort, pageSize: pageSize, userId: userId, nextToken: nextToken).execute().body
    }

    /**
     Returns a paginated list of end-user records for a business
     - GET /users
     - The returned list can be sorted by full name or email address in ascending or descending order. The number of records to return at a time can also be controlled using the page_size query string parameter.  
     - BASIC:
       - type: http
       - name: kindeBearerAuth
     - parameter sort: (query) Describes the field and order to sort the result by (optional)
     - parameter pageSize: (query) The number of items to return (optional)
     - parameter userId: (query) The id of the user to filter by (optional)
     - parameter nextToken: (query) A string to get the next page of results if there are more results (optional)
     - returns: RequestBuilder<Users> 
     */
    open class func getUsersWithRequestBuilder(sort: Sort_getUsers? = nil, pageSize: Int? = nil, userId: Int? = nil, nextToken: String? = nil) -> RequestBuilder<Users> {
        let localVariablePath = "/users"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
            "page_size": (wrappedValue: pageSize?.encodeToJSON(), isExplode: true),
            "user_id": (wrappedValue: userId?.encodeToJSON(), isExplode: true),
            "next_token": (wrappedValue: nextToken?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Users>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
