//
// UserProfile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserProfile: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var preferredEmail: String?
    public var lastName: String?
    public var firstName: String?

    public init(id: String? = nil, preferredEmail: String? = nil, lastName: String? = nil, firstName: String? = nil) {
        self.id = id
        self.preferredEmail = preferredEmail
        self.lastName = lastName
        self.firstName = firstName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case preferredEmail = "preferred_email"
        case lastName = "last_name"
        case firstName = "first_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(preferredEmail, forKey: .preferredEmail)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(firstName, forKey: .firstName)
    }
}

