//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct User: Codable, JSONEncodable, Hashable {

    public let id: String
    public let email: String
    public let fullName: String?
    public let lastName: String?
    public let firstName: String?
    public let isSuspended: Bool?
    public let picture: String?

    public init(id: String, email: String, fullName: String? = nil, lastName: String? = nil, firstName: String? = nil, isSuspended: Bool? = nil, picture: String? = nil) {
        self.id = id
        self.email = email
        self.fullName = fullName
        self.lastName = lastName
        self.firstName = firstName
        self.isSuspended = isSuspended
        self.picture = picture
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case fullName = "full_name"
        case lastName = "last_name"
        case firstName = "first_name"
        case isSuspended = "is_suspended"
        case picture
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(fullName, forKey: .fullName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(isSuspended, forKey: .isSuspended)
        try container.encodeIfPresent(picture, forKey: .picture)
    }
}

