//
// UserProfile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserProfile: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var providedId: String?
    public var name: String?
    public var givenName: String?
    public var familyName: String?
    public var updatedAt: String?

    public init(id: String? = nil, providedId: String? = nil, name: String? = nil, givenName: String? = nil, familyName: String? = nil, updatedAt: String? = nil) {
        self.id = id
        self.providedId = providedId
        self.name = name
        self.givenName = givenName
        self.familyName = familyName
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case providedId = "provided_id"
        case name
        case givenName = "given_name"
        case familyName = "family_name"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(providedId, forKey: .providedId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(givenName, forKey: .givenName)
        try container.encodeIfPresent(familyName, forKey: .familyName)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}

