//
// Users.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Users: Codable, JSONEncodable, Hashable {

    public var users: [User]?
    public var nextToken: String?

    public init(users: [User]? = nil, nextToken: String? = nil) {
        self.users = users
        self.nextToken = nextToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case users
        case nextToken = "next_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(users, forKey: .users)
        try container.encodeIfPresent(nextToken, forKey: .nextToken)
    }
}

